kind: Deployment
metadata:
  name: sample-app
  labels:
    app: sample-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-app
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: sample-pvc
      containers:
        - name: sample-app
          image: busybox
          command: [ "sh", "-c", "sleep 24h" ]
          volumeMounts:
            - name: data
              mountPath: /data